// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

export interface CachedMicrograph { uuid: string, name: string, import_path: string, thumbnail_img: string | null, display_img: string | null, width: number | null, height: number | null, status: Status, created_at: string, updated_at: string, }