// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SegmentStatus } from "./SegmentStatus";

export interface CachedSegment { uuid: string, created_at: string, updated_at: string, binary_img: string, location_x: number | null, location_y: number | null, height: number | null, width: number | null, measured_length: number | null, measured_width: number | null, measured_angle: number | null, measured_midpoint_x: number | null, measured_midpoint_y: number | null, micrograph_id: string, status: SegmentStatus, }