// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Micrograph { uuid: string, name: string, path: string | null, import_path: string | null, thumbnail_path: string | null, file_size: number, file_type: string, status: string, created_at: string, updated_at: string, }