// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

export interface Micrograph { uuid: string, name: string, path: string | null, import_path: string, thumbnail_path: string | null, display_path: string | null, file_size: number | null, file_type: string | null, width: number | null, height: number | null, status: Status, created_at: string, updated_at: string, }