// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueType } from "./QueueType";

export interface QueueItem { id: string, queue_type: QueueType, progress: number, message: string, }