// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueItem } from "./QueueItem";
import type { QueueStatus } from "./QueueStatus";

export interface QueueInfo { status: QueueStatus, current_item: QueueItem | null, }